### ISSUE TITLE
Support custom endpoint

### ISSUE THREAD

**Issue by ibaldonl** [Galillei/magento-sqs#13]
I am trying to use this module with https://github.com/adamw/elasticmq for a simple development environment.
It doesn't seem to support a custom endpoint or I couldn't find the way.
Thanks a lot!

**Comment by Galillei** [comment]
Sorry, I am afraid that I don't understand your question full. Could you please explain what you mean under "custom endpoint" or share links with explanation, and I in my turn will try to help you

**Comment by ibaldonl** [comment]
Hi!
Sorry for not being clear.
A "custom endpoint" means that instead of contacting Amazon's SQS service you contact a clone in another URL (that URL is the custom endpoint).
It is very useful for local development environments without access to Amazon AWS.
It seems that you have a partial implementation of that functionality here for example: https://github.com/Galillei/magento-sqs/blob/master/Model/Config.php#L73
Thanks a lot!!!

**Comment by Galillei** [comment]
O! I understood. Yeah, in current state it is impossible. I will try to fix it during this week.

**Comment by ibaldonl** [comment]
Hello again.
It seems that there are a couple of forks that have implemented the custom endpoint (and have other changes too):
https://github.com/dverkade/magento-sqs
https://github.com/se-sg/magento-sqs
Did you seen them?
Do you have any plans on contacting them to share work?
Thanks!!!

**Comment by sanuter** [comment]
Hi! We're working on it)

**Comment by galillei** [comment]
You can use develop branch, where it is possible to add custom endpoints
