### ISSUE TITLE
Module is not compatible with Magento 2.3

### ISSUE THREAD

**Issue by dverkade** [Galillei/magento-sqs#9]
### Description
The Magento SQS module is currently not compatible with Magento 2.3

### Preconditions
1. Magento 2.3.0 alpha
2. PHP 7.2 or PHP 7.1 (which are compatible with Magento 2.3)

### Steps to reproduce
1. Run the command: "composer require belvg/module-sqs" to install the module

### Expected result
1. Module installs correctly for Magento 2.3

### Actual result
1. Composer throws the following error: 
```
[InvalidArgumentException]                                                                              
Package belvg/module-sqs at version  has a PHP requirement incompatible with your PHP version (7.1.17)
```

**Comment by Galillei** [comment]
Thanks for your report, i merged your requests
